name: cicd-demo
on:
  push:
    branches:
      - '*'
jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Setup Java'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Check Java Version'
        run: |
          java --version
      - name: 'Assemble JAR'
        run: |
          sh gradlew assemble
      - name: 'Get Version Number'
        run: |
          echo "VERSION=$(sh gradlew properties -q | grep "version:" | awk '{print $2}')" >> $GITHUB_ENV
      - name: 'Publish JAR'
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'cicd-demo-${{env.VERSION}}-all.jar'
          path: build/libs/*-all.jar
      - name: 'Start build job'
        run: |
          echo "Starting the build job."